{
  "name": "CI",
  "on": {
    "push": { "branches": ["master"] },
    "pull_request": { "branches": ["master"] },
    "workflow_dispatch": {}
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
        { "uses": "actions/checkout@v2" },
        {
          "uses": "cachix/install-nix-action@v13",
          "with": {
            "install_url": "https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install",
            "install_options": "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve",
            "extra_nix_config": "experimental-features = nix-command flakes"
          }
        },
        {
            "uses": "cachix/cachix-action@v10",
            "with": {
                "name": "usbdm-flake",
                "authToken": "${{secrets.CACHIX_AUTH_TOKEN}}"
            }
        },
        { "name": "Build usbdm (64-bit)", "run": "nix build -L .#packages.x86_64-linux.usbdm"},
        { "name": "Build usbdm (32-bit)", "run": "nix build -L .#packages.i686-linux.usbdm"}
      ]
    }
  }
}
